# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('authors', models.ManyToManyField(to='website.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('review_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Review_is_helpful',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField()),
                ('on_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Review')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('longitude', models.DecimalField(decimal_places=10, default=-1, max_digits=13)),
                ('langitude', models.DecimalField(decimal_places=10, default=-1, max_digits=13)),
                ('status', models.CharField(choices=[(b'AD', b'Admin'), (b'MO', b'Moderator'), (b'US', b'User')], default=b'US', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnedBook',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(b'AV', b'Available'), (b'UA', b'Unavailable'), (b'LE', b'Lent')], default=b'AV', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserWishlist',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(b'RE', b'Read'), (b'CR', b'Currently Reading'), (b'WR', b'Want to read')], default=b'WR', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.AddField(
            model_name='review_is_helpful',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='report',
            name='on_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Review'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='website.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Publications'),
        ),
    ]
