# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 17:39
from __future__ import unicode_literals

from django.db import migrations
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', website.models.BookBenchUserManager()),
            ],
        ),
    ]
