# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171017_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_genres',
            field=models.ManyToManyField(to='website.Genre'),
        ),
    ]
