# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_preferred_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=b'default.jpg', upload_to=b''),
        ),
    ]
