# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='langitude',
            new_name='latitude',
        ),
    ]
