# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_reportuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportuser',
            name='on_review',
        ),
    ]
