# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_reportuser_on_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportuser',
            name='report_user',
        ),
        migrations.DeleteModel(
            name='ReportUser',
        ),
    ]
