# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-07 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20171107_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('on_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_user', to=settings.AUTH_USER_MODEL)),
                ('report_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
