# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20171123_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['ISBN']},
        ),
    ]
